wp-palvelu-plugin.php
`Loader::loadTextdomain` threw PHP notices because the `Loader::domain`
property was referenced without the `self` reference inside the method.
This is fixed and the `domain` property is referenced properly now.
Fixes #18.
=> Fix incorrect reference to `domain` in `Loader::loadTextdomain`

lib/updates-page.php, modules/updates.php
This is a standard security procedure to reduce risk of url abuse.
The form now has a nonce field which is checked by the backend.
=> Add nonce to the form on Seravo update setting page

js/instance-switcher.js
You're not even using jQuery, might as well remove the dependency for it?
We remove jQuery from the client side of themes when we're not using it, which is most of the time nowadays, since it's not 2006 anymore.
=> Use vanilla DOMContentLoaded

js/instance-switcher.js
Fixes #47 .
As it is documented in instance-switcher.php:140, the last item in the admin bar's instance switcher menu is always the docs link. The loop can be stopped before the link.
=> Fix the error when opening docs link 

modules/instance-switcher.php
If the permissions are not checked inside instance-switcher, users can run instance-switcher from somewhere else with their own permissions.
=> Remove the permission check from instance switcher (Closes #55)

modules/optimize-images.php
For the optimize-images page to work properly, the option `seravo-enable-optimize-images` must exist in the database. However, it is not advisable to enable Seravo image optimisation as a default for customers when creating the option.
=> Disable Seravo image optimisation by default

modules/instance-switcher.php
When working in a staging environment, I often have to link to a page inside that environment, but that is surprisingly hard, I have to remember what the query param was, get the instance ID from somewhere, and so on. 
With this, I can just click the big red button, and copy the URL from my browser, or if I'm tech savvy, I can right click the link and copy the address.
Tested and "developed" live @ wp-palvelu.fi instance.
=> Add shadow query string to link if in shadow

modules/purge-cache.php
I told a client to hit the "purge cache" button whenever they have problems, and got "What button, where?" as a response. Naturally I don't want to let them manage all the options, but flushing a cache is something they need to be able to do. 
```php
add_filter('seravo_purge_cache_capability', function () {
return 'edit_posts';
});
```
=> Make purge cache capability filterable

modules/check-https.php
Fixes Undefined variable: siteurl in some cases. 
Ran into this on a multisite that doesn't require HTTPS using Seravo/wordpress.
=> Add undefined variable

lib/api.php, lib/domains-dns.php, lib/domains-page.php, modules/instance-switcher.php, modules/updates.php
Previously, the request implementations were scattered in different modules,
now the code is reusable by invoking the API module.
=> Include separate module for making site API requests (Closes #77)

js/database.js, js/reports-chart.js, lib/database-ajax.php, lib/database-page.php, modules/database.php, style/database.css
- Add database-tool contents in postboxes
- Make postboxes content responsive
- Show database data in pie chart
- Make pie chart responsive
This layout is same as in reports-tool. Also same pie chart from reports-tool, is used showing database table sizes.
I think that pie chart is much more informative and it is faster to see which table takes the most space on database. Also when site content is on postboxes, it is easier to find wanted information from there.
=> Update Database-tool layout to wordpress layout

js/backups.js, lib/backups-page.php, modules/backups.php, style/backups.css
- Make backups-tools content responsive
- Fix code indentation
- Make backups.js file and move JavaScript there
- Make function register_scripts to backups.php
- Make backups.css-file and move css there
I updated backups-tool layout to wordpress layout.
When content are on postboxes it is easier to find what you are looking for. Different tools are more separated and when you go first time to look at the tool, you will see immediately what data and features tool contains.
=> Update backups-tool layout to WordPress layout

js/cruftfiles.js, lib/cruftfiles-ajax.php, modules/cruftfiles.php
Previously the Cruft Files -page did not list multiple files with the same file extension correctly. This lead to situations, where such files could not be deleted.
In this PR files with the same file extension are not stored in an array which is `array_push()`:ed to another array. Rather, each array is merged into one, which also requires changes to `cruftfiles.php`
=> Fix bug of grouping files with same file extension onto same line

.travis.yml, phpcs.xml
This PR includes a ruleset that is created by keeping in mind that we want to primarily
use WP Coding Guidelines, but also have some customizations:
- Use 2 spaces instead of tab indentation
- Multiple assignments don't need to be aligned
- Don't require whitespace around brackets
- No Yoda Conditions
- Don't require class files to be named "class-*"
- Allow usage of PHP exec()
- Don't require all output to be escaped
- Warn about lines that exceed 100 characters
=>  Include new Seravo PHP_CodeSniffer ruleset for unified code style

js/cruftfiles.js, lib/cruftfiles-page.php, style/cruftfiles.css
As stated by @nasusa the postbox-style of layout is better than what was used before. For consistency and usability, in this PR cruft remover uses the same style as most other features in seravo-plugin.
=> Update Cruft Remover layout to WordPress layout

js/updates.js, lib/updates-page.php, modules/updates.php, style/updates.css
- Update updates-tool layout to WordPress layout (postboxes)
- Show technical contact emails in buttons
- Add updates.css -file
- Make layout mobile responsive
I did accidentally delete my latest pr, but luckily I had these files saved to my computer.
=> Update updates-tool layout to WordPress layout

lib/database-page.php
`<p><?php printf( __( 'Adminer is a simple database management tool like phpMyAdmin. <a href="%1$s">Learn more about Adminer.</a>', 'seravo' ), 'https://www.adminer.org' ); ?></p>`
There was typo at a href (was $s, fixed to %1$s) Attribute so link didnt go anywhere.
=> Fix database-tools "Learn more about Adminer" link and translation

js/shadows.js, lib/shadows-ajax.php, lib/shadows-page.php, modules/shadows.php, seravo-plugin.php
In this PR the user is given an option of resetting shadow instances from the WordPress user interface. User can track their shadow instances from a new Shadows page in their Tools menu.
Pressing the ``` Reset Shadow ```-button begins the resetting operation, which is indicated to the user by disabling the button. Successful operation is indicated to the user by changing the text in the button to ```DONE```
=> Introduce feature to reset shadows

js/cruftfiles.js, lib/cruftfiles-ajax.php, modules/cruftfiles.php, style/cruftfiles.css
Removing cruft-files reduces clutter from the users' websites reducing disk usage. However, removing files should be done carefully, and this can be achieved by giving the user more information.
In this PR the cruft remover is enhanced by showing the user the last file modification date and file size.
=> Show more information on suggested cruft-files

js/cruftfiles.js, js/cruftplugins.js, lib/cruftfiles-page.php, lib/cruftplugins-ajax.php, modules/cruftfiles.php, style/cruftfiles.css
This PR introduces a feature which allows the user to remove inactive plugins. The feature also suggests pre-selected plugins that are known to be for some reason unnecessary or cause issues for some users.
When the user has no such plugins:
When the user has plugins that are considered removeable:
When the user clicks one of the trashcans, a notification will appear:
Confirm-notification:
After confirmation and successful removal, the item is removed from the list.
If the removal fails, a similar notification is to be shown.
=> Introduce feature for removing unwanted plugins

js/reports.js, lib/reports-ajax.php, lib/reports-page.php, lib/tests-page.php, modules/reports.php, style/reports.css, style/tests.css
In this changes have been made to the Tests and Reports -pages in order to make future changes easier. The pages are now more similar to how the Cruft remover and Shadows -pages work. With these changes it's easier to redesign the plugin menu layout as described in #98 and #142.
=> Refactor existing Tests and Reports -pages to current architecture

lib/backups-page.php, lib/cruftfiles-page.php, lib/database-page.php, lib/reports-page.php, lib/shadows-page.php, lib/tests-page.php, lib/updates-page.php
Remove redundant div-elements to show WP-notifications in the correct part of the page. Closes #145
=> Fix WP-notification handling

lib/updates-page.php, modules/updates.php
As described in #148 updates-tools currently handle exceptions so that when API can not be reached, the page is not loaded at all.
In this PR the way how such events are handled is changed so that when encountering an error the postboxes are shown. This makes further development easier.
=> Allow updates -tool-page fail gracefully

js/optimize-images.js, lib/optimize-images-page.php, modules/optimize-images.php, style/optimize-images.css
This PR makes the Optimize images -tool use the WordPress-postbox
style.
Currently the Optimize images-option has it's own page in the Tools-menu. To make the Seravo-plugin user experience more unified, the setting must be contained in it's own postbox. This also makes further development easier.
=> Improve Optimize images UI

lib/database-ajax.php
In this PR the database visualization tool shows the total size of the database in a human readable format.
Currently:
New version:
=> Show database size in a human readable format

js/cruftthemes.js, lib/cruftfiles-page.php, lib/cruftthemes-ajax.php, modules/cruftfiles.php, style/cruftfiles.css
This commit adds a feature requested in #93.
The user is not allowed to remove parent themes before all the child themes are removed. Themes are categorized so that relatives are grouped together.
=> Add feature for removing inactive WordPress themes

lib/cruftfiles-ajax.php
This commit fixes the issue #153 by removing sub-directories and files from the listings. This also changes how the cruft remover shows file size information. Previously the shown directory size information was about the first directory within the directory, if applicable.
=> Fix cruft file remover information retrieval

js/cruftthemes.js, lib/cruftthemes-ajax.php, modules/cruftfiles.php, style/cruftfiles.css
This PR fixes #167 
Context for following images: TwentySeventeen is the active theme.
There is only one theme on the page, which is active.
There are some themes on the page. The active theme is not presented to the user for removal.
Avant-X as the active theme
Removing themes...
Removing themes...
SpicePress as the active theme
The page needs to be reloaded at this point to achieve the next view.
=> Update crufttheme remover

style/seravo-postbox.css
Padding from `.inside` class affects all postboxes, adding unnecessary padding to multiple places in the admin, the Publish-postbox for example. These styles are probably meant for seravo-postboxes only. Or maybe this css-file should only be enqueued on seravo-plugin pages?
There are similar risky styles in `seravo-plugin/style/updates.css` but apparently those styles are loaded only on the Updates-page.
=> Fix leaky seravo-postbox padding styles

js/purge-cache.js, modules/purge-cache.php, style/purge-cache.css
Changes to the current mechansim:
- Run `wp-purge-cache` to also empty other caches than the Nginx front cache
- Also display failure message instead of merely success when in WP Admin, log errors to php-error.log
- Use AJAX instead of `wp_nonce_url` => Redirect from JS instead of PHP
- Include a neat cache spinning animation with keyframes :)
***Note:*** for this to work properly, the recent change involving the removation of `wp-restart-nginx` from `wp-purge-cache` must be available.
I haven't myself performed testing this on other sites than my own test site (where it works flawlessly), but will soon do that to find all the scenarios where the mechanism may fail.
EDIT: remember to also test this with other browsers than Chrome.
=> Make "Purge Cache" button run full wp-purge-cache with AJAX (closes #83)

.travis.yml
There have been now a couple of incidents in which the PHP code sniff has
been successful locally, but then failed in the remote Travis CI build to
to different versions of PHPCS and WP Coding Standards. Instead of cloning
the repos directly from GitHub, we should stick to specific releases and
update them periodically.
=> Install specific versions of PHPCS and WP Coding Standards in Travis

lib/api.php
With this it's possible to let the calling function decide if it wants to
handle errors. For example the code 400 (Bad request) could be useful to
not be masked by WP_Error when dealing with zone API.
I have reasoned that this does should not affect the current usage of
the functions.
Maybe add regex to this later? It would be pretty cool.
Examples of usage of the functions:
get_site_data( '/example', [200, 400]);
update_site_data( $data, '/example', [200, 400]);
=> Add optional parameter 'handled_http_codes' to api.php

lib/cruftfiles-ajax.php
With this PR users will not able to remove files that are recommended to be used according to our developer documentation.
=> Omit user from removing whitelisted files

modules/thirdparty-fixes.php
This is more reliable than WP cache functions, that store responses only
temporarily if no object cache has been configured.
=> Use transients for caching API responses

lib/domains-dns.php, lib/domains-page.php
Moves the zones table and the zone editing GUI from below the domains table. Zones are now under the 'view' and 'edit' links of the selected domain.
=> Move zones below the domain

lib/helpers.php
Human_file_size function caused a 'non-numeric value' warning when
opening database-page because 'wp db size' returns a 'B' character
at the end of the value.
Fixed by casting the size argument in to integer.
=> Bugfix: Non-numeric value warning on database-page

modules/check-php-version.php, seravo-plugin.php
The check-php-version.php will check if the PHP version is below the recommendation (7.2.11). If the version is below the recommendation, it'll show a warning message on the WordPress dashboard.
=> Add PHP version checker

modules/relative-urls.php
Previously the code overrode the $content value with transient
even if the transient was false. On top of that, the false was stored as
a transient which was intepreted as an empty string.
Now the transient is a separate value, so mixups won't happen.
Try to curl a site's feed (the site should have feeds as full posts enabled). In master, the feed does not include the whole posts. 
Then change to this branch, flush cache and curl. Full posts should be visible now :) See #197 for the original issue
=> Fix transient handling in relative urls in feeds (Closes #197)

lib/domains-dns.php, lib/domains-page.php
Adds primary domain indicator.
Removes zone actions for domains that can't use them (subdomains and domains not managed by Seravo) and shows message instead. Suggested in #203 
Replaces the default zone edit submit button with a proper one.
=> Zone edit improvements

js/updates.js, lib/updates-page.php, modules/updates.php, style/updates.css
The Seravo-plugin UI should be uniform. This PR moves the image comparison tools to a postbox-ish element already on the Updates-page.
When no images are found:
Images found browser window is narrow:
The difference image is available from the link beside the percentage value.
In order to test the feature fully, you need at least three images png in the `/data/reports/tests/debug/` directory. You can optionally use my site to test this feature.
Open for any further usability advice and development.
=> Update Updates-page image comparison UI

lib/domains-page.php, modules/mails.php
Adds minor fixes to prevent PHP notices with WP_DEBUG enabled and makes the action links below the domains translatable.
=> Fix warnings and improve translatability

lib/domains-page.php, modules/logs.php
Adds null-checking to domain and log -pages. These
pages otherwise give PHP-warnings with WP_DEBUG enabled.
Logs-page has been designed so that it doesn't try to
use log files that don't exists. But always using
'php-error.log' as default didn't verify its existence.
=> Add null-checking to suppress PHP-warnings

docs/README.md
This PR adds Seravo-plugin documentation describing the use of Postboxes. This documentation enables developers to create cleaner looking admin tools easily using Postboxes.
The documentation should be clear, understandable and following it should allow developers to create new Postboxes.
Closes #224
=> Add documentation on postboxes

js/cruftplugins.js, js/cruftthemes.js, modules/cruftfiles.php, style/cruftfiles.css
This pr closes #215.
I think that after this pr cruft plugin is more pleasant to use. Plugin has consistent layout, and you can select all cruft files, plugins and themes; and delete them.
_In cruft themes, if theme has a child theme it will be bolded and can't be deleted before child theme._
=> Add new layout to cruft plugin (Closes: #215)

js/domains.js, lib/domains-ajax.php, lib/domains-dns.php, lib/domains-page.php, modules/domains.php
Implements zone editing using AJAX (as originally planned in #182) and makes it more user friendly.
Improvements:
- No need to load the page again (Can be annoying with larger domain lists).
- Don't need to start over when trying to save invalid zone.
- Gets sanitized version of zone right after saving.
- Disables editing with errors (eg. Record fetch failed) to make accidentally breaking zone harder.
=> Implement zone editing using AJAX

js/security.js, lib/security-ajax.php, modules/security.php, style/security.css
This pull request adds postbox to security.php page and shows 10 latest successful logins from the wp-login.log and if wp-login.log doesn't have enough entries it will get the rest from the rotated log files. Ajax spinner populates the postbox until the login information is gathered.
Function has now only parameter for maximum results showed. Username seemed unnecessary as this is visible only to admin and for admin we wanted to show all the logins. Minimum parameter is also left out because opening rotated files is fast and I didn't see a real need to have a minimum to give up opening rotated files. Implementing geolocation will require installing PHP extension so that will need to be added later.
Relates to issue: https://github.com/Seravo/seravo-plugin/issues/6
=> Add postbox which shows 10 latest successful logins to security page

lib/security-ajax.php, style/security.css
This will add CSS ellipsis also for IP address. Currently if postbox happens to be really narrow and the IP is near the maximum length of 15 characters the last digits of the IP are written over the username. This bugfix will shorten the IP and add it in a tooltip if the IP doesn't fit otherwise.
Currently:
With IP ellipsis:
Narrow:
Wide:
=> Add ellipsis also for IP address

js/cruftthemes.js, lib/cruftthemes-ajax.php, modules/cruftfiles.php
This fixes multiple bugs related to cruft themes remover:
- Possible to remove active themes on multisites
- Possible to remove parent themes with 'select all' checkbox
- Removing themes duplicates the table
- Confirmation is asked multiple times
Also adds small UI changes left out at some point. 
First bug reported in #254 
Testing if the cruft themes remover works as expected should be enough. It
should be done on multisite (joosuatesti @ ams-test1 can be used, it's already using these commits).
=> Fix cruft themes remover bugs

modules/updates.php
Fixes the incorrectly displayed empty update.log contents by checking that there is content to display. Also adds missing translations to Updates page update notification and links.
If there is an issue related to this PR, please link it here for context.
Issue: #262 
2b87e5d fixes the empty display and should be checked that it now functions correctly. If update.log has no content to show but the full update has not been succesful, only the notification should now display. If the update.log has lines starting with "Updates failed!" those lines are shown.
1b761ef adds translations
=> Fix #262 (Update summary blank on some sites, should never be)

modules/fixes.php
Forces updating of 'alloptions' in cache. Some WordPress-hosts 
are running similar fixes. Issue explained in the [commit message](https://github.com/Seravo/seravo-plugin/commit/95f03d047917cb7e88e51140182a6c7752b0ef48). 
The issue has caused problems on some customers but
affects everyone.
This has already been tested on some sites and probably 
doesn't need more testing. The performance impact has also been
tested with `wp-speed-test` and no clear difference was noticed.
If the issue needs to be reproduced, it should be possible like this:
1. Run `while sleep 0.1; do wp option set debug-option $(openssl rand -hex 1); done`
2. In other shell instance, update some option key a until it stops working (refuses to change):
Previous shouldn't be possible with the fix applied.
=> Fix alloptions not updating in cache

js/tests.js, lib/tests-ajax.php
Fixes the checking of failed tests by changing the checking of "Failed examples" string to check the return value of wp-test instead. Update Tests postbox now displays failed tests correctly if the return value of wp-test is non-zero.
Issue #243
=> Fix display of wp-test results on Tests page

js/updates.js, lib/updates-ajax.php, modules/updates.php
This change will add Seravo Plugin Updater.
A pictures of the change
New update available:
Latest version:
=> Add Seravo plugin updater to the Updates subpage

js/shadows.js, lib/shadows-ajax.php, modules/shadows.php, style/shadows.css
This redesigns shadows page to be more like mails-page. The postbox width is no longer
forced to 100% to support multiple postboxes on the same page. Now that shadows work
better with custom domains, I also added 'domain' field and search-replace instructions.
These changes were supposed to come with wp-shadow-pull feature but I made this now
separately as there's some problems with it and I don't want to slow down toolbox update development. 
This was planned in wp-shadow-pull issue comments.
=> Redesign shadows postbox

modules/instance-switcher.php
Fixes #274.
Load switcher assets only if user is logged in or in staging.
`instance-switcher.js ` is loaded in front-end even when user is logged out. And it even has dependency of jQuery. This should not happen when user is logged out (regular site user).
=> Load assets only if user is logged in or in staging.

js/updates.js, lib/updates-ajax.php, modules/updates.php
Adds a button for running the wp-php-compatibility-check to the Updates page
of seravo-plugin. Once the check is done running, the number of errors found
is displayed to the user. If the check exits with a non-zero exit code, the
button is re-enabled and an error is displayed.
#271
=> Add GUI for PHP compatibility check

lib/search-replace-ajax.php
Add check for the third line of wp-backup output to search-replace-ajax.
Currently, search-replace-ajax check only if the fourth line of wp-backup output is "Success: Exported to 'example.sql'". But some sites wp-backup output not contains "No path given as argument. Using default path." and "Success: Exported to 'example.sql'" is in the third line of output. This causes search-replace failing.
Before change:
After change:
=> Check the exit code of the wp-backup command on search-replace ajax

lib/seravo-postbox.php, style/seravo-postbox.css
This PR will add an optional two column page layout to postboxes. Also, in two column postboxes, if window width is more than 2300px, it will limit postboxes width to 1050px.
The issue #233
Set any add_submenu_page() look like:
```
add_submenu_page(
'tools.php',
__('Example', 'seravo'),
__('Example', 'seravo'),
'manage_options',
'example_page',
'Seravo\seravo_two_column_postboxes_page'
);
```
width 1920px:
width 3840px:
=> Add 'two column' postboxes page layout

js/cruftplugins.js, js/sitestatus.js, js/upkeep.js, modules/security.php, modules/sitestatus.php, modules/toolbox.php, modules/upkeep.php, seravo-plugin.php, style/domains.css
The main changes in this PR are the fixes for bugs that came with the Seravo Toolbox.
Issues #287, #290, #291 and #292
Testing in shadow or vagrant with seravotest account and another account which is an administrator account.
1. In the shadow or vagrant, check toolbox pages
2. In multisite WordPress, test with seravotest < site >/wp-admin
3. Test optimize-images from Site Status
Vagrant Multisite WordPress in wordpress.local/wp-admin with seravotest:
Vagrant Multisite WordPress with admin account:
Production with admin account:
=> Fix bugs that came with the Seravo Toolbox PR

modules/fixes.php
We have not used this feature for years so it can be considered deprecated.
We might want to reintroduce it some day, but it needs to be re-written
to use the SWD API etc. Now it is just best to remove it as it will also
stop the various sites from bombarding wp-palvelu.fi on every wp-admin
dashboard page load.
=> Remove WP-palvelu.fi notification fetcher

lib/domains-page.php, modules/upkeep.php, modules/wp-cli.php
This PR include fixes for the next things:
- Fix a few typos in the upkeep page code
- Change usort_reorder to usort_reorder_mail in the domains page code
- Fix a bug in wp-cli that causes error message on command `wp seravo updates` when Seravo Updates is disabled
Testing:
- On the upkeep page, disable or enable Seravo updates and save settings
- View the zones in your domain
- Once Seravo updates is disabled, run `wp seravo updates` in the site CLI
=> Mixed fixes for Seravo Plugin

modules/logs.php
Decrease the value of the "limit" attribute.
#298
1. Go to the Logs page
2. Choose a log file that contains more than 50 lines. (Example: wp-php-compatibility.log)
3. Scroll to the first line of the log file.
=> Decrease the value of the "limit" attribute in while-loop (Closes: #298)

js/sitestatus.js, lib/sitestatus-ajax.php, modules/sitestatus.php, style/sitestatus.css
Improves the Redis info looks, replaces the curl with `wp-check-http-cache` and
adds parsing of `/data/slog` for historical info.
Issues #281 and #72 .
**Old:**
**New:**
=> Add cache status improvements

lib/security-ajax.php, lib/sitestatus-ajax.php
Fixes the warnings on freshly deployed sites.
Reported in #303.
Deploy a new site and go through the Seravo Plugin
tools (especially site status and security).
=> Fix PHP-warnings on new sites (Closes: #303)

modules/instance-switcher.php, modules/sitestatus.php
Reduces amount of SWD API calls made on couple of places. Most importantly,
instance switcher doesn't query domains for each shadow individually
on every page load when logged in anymore.
Reported in #304.
Load page on a site with shadows while logged in and
monitor the amount of API calls made.
=> Reduce amount of SWD API calls (Closes: #304)

modules/thirdparty-fixes.php
Prevent Redirection plugin from ever enabling redirect caching.
While doing site upkeep we've noticed many times issues with redirects
getting cached too aggressively, which in turn sometimes causes redirect
loops (and eventually blocks access to site).
We hook up using filters provided by Redirection plugin, and always set
`redirect_cache` to disabled status (0). This is fine, as our
infrastructure does caching anyways, and ensures best results for end
user.
I'll provide backlink from another issue.
Ensure that this
1) doesn't break anything
2) disables redirect caching
1) setup test site
2) install Redirection plugin (NOTE: you need probably to go through setup via wp-admin)
3) enable Redirection plugin
4) check `redirect_cache` status, should be `-1`, eg. `wp eval …
=> Disable Redirection redirect cache

modules/fixes.php
A similar fix has been implemented in WP core 5.3.1 and has
been tested. Running two of these fixes at once was found
out to be more harmful.
The fix is now only ran with WordPress versions lower than 5.3.1.
Issue #314.
=> Deprecate alloptions fix (Closes: #314)

modules/upkeep.php
Fixes incorrect "Test status" on upkeep page.
Issue #307.
Using the oneliner from command line is probably the easiest way to test this issue and fix.
=> Fix checking baseline test status from logs

js/passwords.js, modules/passwords.php, style/passwords.css
Updates the weak password disabling to affect lost-password screen too. This both hides the checkbox and disables the button if it was enabled for some reason.
Issue #322. The old fix didn't affect lost-password screen as the weak password option didn't exists there at the time. 
In the issue #322.
=> Disable weak password option (Closes: #322)

lib/helpers.php, lib/security-restrictions.php, modules/security.php, style/security.css
- XML-RPC blocking is now enabled by default
- Jetpack is whitelisted from XML-RPC blocking
Closes: #297
=> Use XML-RPC block by default and whitelist Jetpack

lib/security-ajax.php, style/security.css
Sites not using UTC are currently only shown an empty table
on security page login history postbox.
Also the whole parser code was very annoying to read so I simplified it a bit. Using regex is probably not the best way to make it more readable but it now takes care of the whole parsing process and is very easy to understand.
This was a problem on a site.
=> Fix login history only working on one timezone

js/backups.js, js/upkeep.js, lib/search-replace-ajax.php, lib/security-ajax.php, lib/upkeep-ajax.php, modules/backups.php, modules/logs.php, modules/security.php, modules/upkeep.php
Improvements to Seravo Plugin compatibility with Vagrant. Some of these are also really small improvements to Seravo Plugin overall:
**[Backups postbox]**
- Show 'no entries' instead of empty postbox.
**[Upkeep page]**
- Fix JS errors breaking the page.
- Don't show PHP-version changing postbox only in production.
- Check if PHP-version change was successful 5 times instead of just once. This is because Vagrant might be a bit slower and the first requests are likely to fail and give false errors (like during nginx restart). Also improve the errors.
- Don't use production-only commands during PHP-version change.
- Fix empty Seravo Plugin upstream version.
**[Search-replace postbox]**
- Fix PHP-notices.
**[Logins info postbox]**
- Don't show logins info postbox only in production.
- Show …
=> Fix bugs in Vagrant env (Closes: #323)

modules/passwords.php
To improve security, passwords are now checked on login with `wp-check-haveibeenpwned`.
The checking is made only if it has been 90 days since last check or if the last check had failed / found pwned password. If `wp-check-haveibeenpwned` found the hash, a warning page in the image is shown.
=> Show alert for pwned password

js/instance-switcher.js, modules/instance-switcher.php
We have been using seravo_shadow as the cookie name for 2 years at least.
All references to deprecated legacy wpp_shadow cookie must be removed.
This probably also fixes cases where the instance switcher was reading
the old cookie and not at all the correct seravo_shadow cookie.
=> Remove all use of deprecated wpp_shadow cookie (should be seravo_shadow)

modules/optimize-on-upload.php
This can be tested by uploading high quality jpeg images to the WordPress media gallery with and without this code enabled, and then compare the visual look of the images.
=> Override default WordPress jpeg quality with a better value: 90

modules/optimize-on-upload.php
The new version of wp-optimize-images is either slow or has some bugs
in exec() spawning or performance. Disable this for some time to get
until the new tool is optimized.
=> Temporarily disable real-time image optimizations

js/sitestatus.js
Found on /wp-admin/tools.php?page=site_status_page
Previously, the width of the bar was always 'auto', because the ratio was
miscalculated.
Adding the `* 100` to the calculation fixed the issue, but it caused some of
the numbers to wrap. I added a second div, which prevents the wrapping.
Before:
After:
=> Fix the width of the HTTP request bars

lib/security-restrictions.php
For whatever reason, jetpack.com responses randomly with 429,
when the user agent is WordPress/x.x.x.
Also, include https://seravo.com as url in the user agent, so
Jetpack knows who to contact in case of problems.
=> Use SeravoBot user agent when requesting jetpack ips

modules/optimize-on-upload.php
Do so in two ways:
1) Pass 3 extra command line values the PHP process already knows to
the Python wp-optimize-images command, so that it can avoid doing
any 'wp option get' itself, and thus save 1-2 seconds per invocation.
```
$ time wp-optimize-images 1568x2844.png
...
real	0m1.959s
$ time wp-optimize-images --enable --set-max-resolution-width=4000 \
--set-max-resolution-height=4000 1568x2844.png
...
real	0m0.204s
```
2) Redirect output and background command so that exec() returns to PHP
and continues without waiting.
There is no need to synchronize the roll-out of this with the roll-out
of the new version of wp-optimize-images.
This is safe to roll-out at any time, since if the --enable or other
arguments are not yet available in the environment, they the command will
just fail but …
=> Make calls to wp-optimize-images run much faster

modules/fixes.php
Stops forcing HTTP 401 for unauthorized AJAX calls. Some plugins require
unauthorized use of admin-ajax and they require a HTTP 200 response.
Issue: #347
=> Don't force HTTP 401 for unauthorized AJAX calls

modules/logs.php, modules/wp-plugin-log.php, seravo-plugin.php
Log plugin and theme activations, deactivations, installations, updates and deletions in /data/log/wp-settings.log file. Tracks date and time and the user who is making the change. 
Currently theme deletions are not logged as there is no hook for it.
Related issue: #329
=> Add plugin and theme logging

modules/hide-users.php, seravo-plugin.php
Hide Seravo-specific WordPress users from user listings by using the `pre_get_users` hook. Users `seravo` and `seravotest` will be hidden as defined in commit b57b33b. The ability to hide certain users from the front-end was discussed in the issue https://github.com/Seravo/wordpress/issues/46.
Works for the Users page in WordPress Admin and the CLI command `wp user list` but the effect should be tested for some user listing plugins. The hidden user can see itself on the lists if they are logged in.
=> Hide specified users from user lists

lib/cruftfiles-ajax.php
Extend the cruft remover to detect clear backup and temp files as well as some well-known unnecessary files.
The cruft remover already had some common patterns for backup and temp files and this extends the list of them. OSX metadata file DS_Store should also be marked as cruft together with misplaced .htaccess and db.php files.
=> Include more evident cruft files in the cruft remover

js/upkeep.js, modules/upkeep.php
Translations needs to be done
This PR adds a few bug fixes and enhancements for the technical contact email handling on Upkeep page. There must be at least one valid email address and user is notified by this if they're trying to remove all emails. Emails are now on also required to be unique so user can't add/spam multiple same emails. Email input value text is reset after adding a new email. 
Issue #124 and #374
=> Add empty check for contact emails (Closes: #124)

modules/logs.php
Prevents reading of log files over 256MB.
Multiple issues about wp-admin not working with huge log files.
=> Prevent reading huge log files

js/domains.js, lib/domain-tables.php, lib/domains-ajax.php, modules/domains.php, style/domains.css
Adds mail forwards table to mails postbox on domains page.
The actions available are:
- Fetch forwards for a domain
- Create a new forward for a domain
- Delete a source and its destinations
- Modify the destinations of a source
- Modify the source
Closes: #13 
These actions must be tested with a domain under Seravo's management.
After fetch:
Editing:
=> Add mail forwards table

README.md, lib/domain-tables.php, lib/domains-ajax.php, lib/seravo-postbox.php, modules/passwords.php, phpcs.xml, scripts/install-phpcs.sh
- Rewrite PHPCS installation script to be simpler and more of a direct
copy of that in Seravo's development environments.
- Upgrade PHP CodeSniffer from 3.3.2 to 3.5.5 and fix the new issues it
detected:
* Update phpcs.xml to ignore date() warnings, since we on purpose want
to show the localized time to users.
* Run phpcbf to automatically fix a bunch of issues, including use
time() instead of current_time('timestamp', true) as standard
recommend. Both output the exact same thing:
```
$ wp shell
wp> current_time('timestamp', true);
=> int(1593535321)
wp> time();
=> int(1593535324)
```
=> Document how to easily run PHPCS (Closes: #346) and update PHPCS

lib/cruftfiles-ajax.php
List .tmp files and .old files and dirs as cruft.
Also list some more known cruft file and directory paths. Detect misplaced adminer.php.
=> Extend cruft remover to detect more files and dirs

lib/domain-tables.php, lib/list-table.php
Forks class-wp-list-table.php from WordPress upstream.
**Downsides:**
- Needs to be updated from time to time
**Upsides:**
- Production sites don't break if customer updates core by themselves
- Follows WordPress codex
- Doesn't need to be updated often (Only syntax and documentation changes for a couple of years)
- Seravo Plugin implentation of wp-list-table is kind of a hack and if we want to, this allows us to get rid of some bad code
https://github.com/Seravo/seravo-plugin/issues/54
=> Fork class-wp-list-table.php (Closes: #54)

modules/wp-login-log.php, modules/wp-plugin-log.php
Logs were ending up in random places.
This fix sets a fixed location for the logs to '/data/log/' folder.
Closes #378
=> Change log location to a fixed folder

js/sitestatus.js, modules/database.php, style/database.css
Set the vertical align of dashicon icons to middle so that they are inline with button text.
Now all buttons with icons are like the one at the bottom. Other ones are examples of the previous look.
=> Fix dashicon align inside buttons (Closes: #386)

modules/hide-users.php
Add a condition to hidden users module so that hidden users are shown with WP-CLI commands.
For instance, `wp user list` now shows all users but the ones defined to be hidden, won't show up in the web front-end.
Improves user management in the command-line.
=> Show users with WP-CLI

js/reports-chart.js, js/sitestatus.js, lib/sitestatus-ajax.php, modules/sitestatus.php, style/sitestatus.css
Use apexcharts.js for disk space postbox, implement a chart for total used disk space and redesign the per-directory chart.
Per-directory chart is now a bar chart that shows the size of certain directories listed in `sitestatus-ajax.php`.
The following logic is also followed:
- any directory under `/data` is shown
- all directories with size less than 1MB is not shown
- size of Seravo backups is not counted in the total used space nor is the directory listed in the bar chart
The donut chart for total disk use provides a simple view on how much of available space is used and the bar chart
provides a quick way to see what parts of the site take a lot of space.
=> Enhance disk space postbox

js/sitestatus.js, modules/sitestatus.php, style/sitestatus.css
The items in shadows box are rearranged to a table and some of the instruction texts are updated.
Translations are not done.
Shadows box needed redesign to be more user friendly.
Issues: #288 #277
1. Create a shadow (if you don't have one already)
2. Make changes to production site
3. Go to Tools --> Site Status --> Shadows
4. Select a shadow from table
5. Read shadow information
6. Click "Reset"
7. See that the shadow was reset from production
=> Redesign shadows box to table (Closes: #288 #277)

js/upkeep.js, lib/upkeep-ajax.php, modules/upkeep.php, style/upkeep.css
Adding GUI for wp-backup-list-changes-since command and thus providing customers an easy way to see file / folder modifications between backups. We've as well been discussing about bringing the backup restoring feature so this could potentially be one step towards that. Users can track down what have changed between backups and possibly use this to choose which backup they should restore. 
Translations are yet to be done. 
We've been discussing and planning this feature during the sprint. 
Here's the basic GUI
After the run results / affected rows are shown in the toggle box. OBS, the rows affected shows now 5 rows since I modified HTML so this is no real bug.
=> GUI for wp-backup-list-changes-since

js/cache-status-charts.js, js/sitestatus.js, lib/sitestatus-ajax.php, modules/sitestatus.php, style/sitestatus.css
Cache hit rates are presented with horizontal bar graphs.
Titles and instruction texts are rewritten. Some links to documentation and blog to help the user to interpret the provided values are added.
Translations are not done yet.
The content of Cache Status postbox has been hard to interpret and understand. The changes in this PR make the postbox content more approachable and provide the users links to external sources to learn more about the topic.
1. Go to Tools --> Site status
2. Look at Cache Status postbox
3. Read the contents of the postbox
4.  Check the links
5. Hover your mouse over bar graphs and info-icons
=> Modify Cache Status postbox content to be more informative

modules/logs.php, modules/wp-user-log.php, seravo-plugin.php
Log following changes in users to /data/wp-user.log file:
- User is created by another user
- User registers
- User's email is changed
- User's password is changed
- User is deleted
- User's role is changed
- User resets password
Related #329
=> Log important WordPress user changes

js/sitestatus.js, lib/sitestatus-ajax.php, modules/sitestatus.php, modules/speed-test.php, seravo-plugin.php, style/sitestatus.css, style/speed-test.css
Under Tools -> Site Status there is now block for Speed Test to run tests to different urls within the wordpress site. The test runs multiple curl commands from within the server to see the speed of generating the html from php. The tests are run with both with and without cache enabled.
The chart uses ApexCharts library, which is the same library as the one used in #391. 
There is button in the wordpress admin bar to test the speed of current page using the above mentioned GUI.
Before the speed test was only available from the CLI. With this the feature is more easily available to more people.
The result chart of a successful speed test:
Button for the speed test in the admin bar:
=> Add GUI for speed test

js/sitestatus.js
Turning off either of the legends while the speed test is running breaks the apex chart.
Making them non-toggleable fixes this issue.
Closes #402
=> Make chart legends non toggleable

modules/sitestatus.php, modules/speed-test.php, style/speed-test.css
Speed test button is changed to lead to the site status page where the speed test is. Added an explanation text to the speed test block to say that the test can not be ran within wp-admin.
Closes #398
=> Adjust speed test button in adminbar

js/reports-chart.js, lib/sitestatus-ajax.php, modules/sitestatus.php, style/sitestatus.css
Before only 5 of the largest directories were included in the chart. Remove this limit because there is no reason to have it in place and users cannot see all the culprits for low disk space. Since now the number of directories can be really big, there is now a wrapper that makes the list scrollable if it becomes too large. The dir names can be really long, so they are now aligned so far to the left as possible. Because of the scroll bar, dir paths didn't always fit the screen very well and were cut off. Apex Charts tooltips have been enabled and configured now.
**Just a few dirs**
**Tons of dirs**
Test dirs were created with
```
$ wget https://speed.hetzner.de/100MB.bin
$ for i in {1..50}; do mkdir d$i ; done
$ for i in {1..50}; do cp 100MB.bin d$i/tiedosto ; done
```
=> Do not limit the number of shown large dirs and fix styling

js/cache-status-charts.js, modules/sitestatus.php
The texts of cache status charts are added for translation.
All texts in plugin should be translated in Finnish.
=> Cache status chart texts to translation

js/database.js, js/reports-chart.js, modules/database.php, style/database.css
Change database chart library to Apex Charts.
Use a bar chart instead of a pie chart.
If there are many plugins, for instance, the number of database tables can be really big,
so there is now a wrapper that makes the list scrollable if the number becomes too large.
Database table names are also aligned as far left as Apex Charts allows because table names can be long and be cut off.
Because of possible long names and the scroll bar introduced in this commit, there are now Apex Charts tooltips that have
the same information as the bar themselves.
The bar chart is clean and I don't think there is need for other types of visual elements here.
The chart provides an easy way to see which tables are the largest and shows the exact size of all of them.
=> Use a bar chart as database chart (Closes: #397)

lib/upkeep-ajax.php
Currently style format codes are produced when running wp-test on Seravo Plugin. I have implemented a regex replace together with @sjaks to remove these excessive styling character codes. 
For instance, section Acceptance Tests had these "[1m" formatting characters:
[1mAcceptance Tests (2) [22m---------------------------------------
=> Enhance wp-test result by removing excessive characters

lib/sitestatus-ajax.php
Strings are fixed to match all log rows instead of just rows with string "Seravo".
Before, only the total access log rows with text "Seravo" were matched. However, all the rows with relevant data should be matched to get the real HTTP hit rate.
=> Fix strings to match all relevant total access log rows

style/upkeep.css
Add a small fix for seravo-result-wrapper having max-width which causes some misconformt on bigger screens. This also enhances the whole view since now the free space is used more effectively. 
The current setup is that the max-width is defined
After the fix seravo-result-wrapper class should have the width based on it's parent width
=> Enhance seravo-result-wrapper to have width based on it's parent width

js/reports-chart.js, js/sitestatus.js, lib/sitestatus-ajax.php, modules/sitestatus.php
The total disk space donut chart only had number values on the tooltips. Since they are always in MB, add the MB sign after the values.
Fixed the logic of calculating the used disk space and showing certain directories. Now directories are shown with the following logic:
- certain directories are always fetched
- directories with more than 100MB are always fetched
But there are directories the sizes of which are not counted in total usage:
- /data/backups
- /data/log
- /data/slog
Also, content of /data/backups are never shown even if their sizes exceed the 100M threshold.
This means the total disk usage is the size of /data minus the three dirs listed above.
=> Fix and improve disk chart

modules/speed-test.php
Check that user has access in same way as it's done with purge cache and shadow instance switcher.
Closes #411
=> Remove speed test button from normal users

modules/sitestatus.php
It was possible to put values such as '100asd' as width and height.
Now the values are checked to make sure they're proper numbers.
Seems php has interesting ways of comparing values. 1000 < '2000asdf' returns true even when the other is a string and with extra non-number characters!
Closes #415
=> Fix optimize images input validation

modules/login-notification.php
Add hook for showing last login notification on profile page. Subscribers are normally redirected to their profile page after they login to wp-admin. Last login will be shown for them too.
Related issue #7
=> Show user last login for subscribers too on profile page (Closes: #7)

js/database.js, lib/database-ajax.php, modules/database.php, style/database.css
Implement a toggle menu under the Database size postbox and show details about database tables and sizes in it.
Implements the same functionality as the command `wp-db-info`.
=> Show more details about database tables (Closes: #163)

js/upkeep.js, modules/upkeep.php
Add feedback to the user if the php-compatibility ajax check takes too long.
Related #315
TODO: Translations once the code is ok.
=> Add error feedback on php-compatibility timeout

modules/login-notification.php, modules/logs.php
Abnormally long lines in the log file cause the admin panel to freeze. 
Now if too many chunks are generated while reading the log file, give up reading the log file to prevent the admin panel from freezing and return false like with too large files.
This does not fix the underlying issue that there is such log files though, and is a band-aid to stop the admin panel from freezing.
=> Fix admin panel freeze with too large php-error log

lib/database-ajax.php
The tables ought to grow really long and the bottom two queries already has limits of 15.
Added limit of 15 to all queries that produce lists under the database table details menu.
(Closes: #426)
=> Add limits to database table detail queries

js/sitestatus.js, languages/seravo-fi.po, languages/seravo.pot, modules/sitestatus.php, style/sitestatus.css
The user is now informed when the ajax call times out.
When the ajax returns 504 timeout message the user now gets an error message about it.
Unfortunately there is no easy way to know if the shadow is actually resetted or not.
Related #315, #187
TODO: translations once code is ok
=> Add timeout error message to shadow reset

modules/svg-support.php, seravo-plugin.php
After this change, administrators can upload SVG images to media library. SVG is not sanitized.
Related issue: #356
1. Login as an administrator.
2. Try to add SVG image to media library.
4. Log in as a non-admin user.
5. Try to add SVG image to media library.
=> Add support for SVG images

js/database.js
Before the autoload table size was incorrectly calculated in the Database details list. Calculate it correctly and show as MB.
=> Bugfix: fix database autoload size correctly (Closes: #431)

modules/wp-user-log.php
Remove undefined, unused variable.
Reported by @ypcs
=> Remove an undefined variable

js/sitestatus.js, modules/sitestatus.php
Handle API error when available disk space cannot be retrieved by
averting from generating the disk donut chart and hiding the
wrapping element.
Fixes bug where other charts couldn't be rendered on the same
Site Status page if generating the disk donut failed.
=> Do not render disk donut if available space cannot be retrieved

js/sitestatus.js
Speed test labels used to go over each other when the latency averages were too close to each other.
Now the lower value's label is underneath the line.
Worst case scenario where the labels would have been right over each other looks like following now:
Closes #430
=> Fix speed test label overlap

style/seravo-postbox.css
As described on issue #438 updating to WordPress 5.5 causes Seravo postbox lose their top stylings. This adds manually some css styles so that Seravo postbox top stylings work as intended on WordPress 5.5 versions too. The fix doesn't interfere with later than WordPress 5.5 postbox styles. 
Some more investigation might be required to find out whether the issue can be closed or apply another patch.
=> Temporary quick fix for Seravo postbox styles missing

modules/check-default-email.php
Extend the check for bad admin emails by listing unwanted emails
in an array. Include noreply@, no-reply@ and vagrant@.
This is a needed feature since having a no-reply or vagrant email address can make it impossible to receive WP emails.
Changing WP admin email to something like `wp option set admin_email noreply@seravo.com` should yield:
=> Extend admin email checking

modules/svg-support.php, seravo-plugin.php
PHP below version 7.0 does not support the `levels` parameter of `dirname`.
This fix uses a compatible way to traverse up the directories.
=> Fix PHP<7.0 compatibility issue with SVG support module

modules/wp-plugin-log.php, modules/wp-user-log.php
Make it clear when plugin and theme changes were made from WP-CLI.
Log username of the user whose role is being changed.
Exclude seravotest user from the wp-user.log
=> Fix wp-user and wp-plugin logging

js/domains.js, modules/domains.php
The mail forwards were not rendered correctly, because "Forwards" was
hard-coded and it happened to be a translatable string.
=> Fix mail forwards language incompatibility

js/sitestatus.js, modules/upkeep.php, seravo-plugin.php
Instead of passing GoAccess reports or Codeception screenshots via PHP
(thus reserving one PHP worker for the duration of the download) let Nginx
handle it with the X-Accel-Redirect header.
This can be rolled out only once the server side X-Accel-Redirect settings
are in place.
=> Implement generic X-Accel-Redirect function and use if for screenshots

js/sitestatus.js
Fix the permanent "Running cache tests..." and show the HTTP cache status.
See issue #470
=> Fix not showing HTTP cache working status (Closes: #470)

js/sitestatus.js, lib/sitestatus-ajax.php, modules/sitestatus.php
Add a nag bar to the site status page onto Cache Status postbox to notify user about missing/disabled object-cache.php and button for easy one-click installation. Also remove any excessive object-cache.php.* named files at the installation process. 
Translations still to be done.
See issue #463
Nag for missing/disabled object cache
Successful installation
=> Add a nag and one-click installation for missing object-cache.php

modules/sitestatus.php
Set the new image optimization max dimension to 2560px. This height and width value have been enforced since WordPress 5.3 version as it's stated on the issue #471
=> Set new default max image dimensions (Closes: #471)

js/upkeep.js, lib/cruftfiles-ajax.php, lib/upkeep-ajax.php
Ensure that all the modules under the lib/ or modules/ use proper naming conventions like using Seravo namespace or seravo_ prefix on function names. Since we have been using seravo_ prefix on function names on ajax side anyway, I didn't make any major namespace related modifications. 
Some notices, I didn't force Seravo_Domains_List_table class (lib/domain-tables.php) to use Seravo namespace since the instance of this class is only used on domains-ajax.php where seravo_ prefix is already used on handling. The namespace usage would have also caused quite a lot refactoring on lib/ and modules/ regarding the domain view. JS modules have been left out since the issue doesn't really consider them and I think they are not so important when it comes to this namespace / prefix thing. 
See issue …
=> Ensure seravo prefix or namespace usage on modules (Closes: #466)

modules/check-default-options.php, seravo-plugin.php
The module sets checks for default options, and if they are not set, it sets the missing options on.
Closes: #472
1. Removing said options from a development site, and generating them back using the module
2. Setting an option to be not used, and test that the module does not overwrite it
=> Create check-default-options module

modules/login-notification.php
There were some excessive `error_log()` usage on login-notification.php module that caused empty lines to php-error.log with only timestamp on them. This removes those excessive errors.
See issue #487
=> Fix excessive error logging (Closes: #487)

style/database.css
The English language version of the plugin had some issues with the alignment of the input elements. The problem was the words "From" and "To" being different length. Giving the labels a width fixed the issue.
**Screenshots before and after**
=> Fix input element misalignment (Closes: #483)

modules/thirdparty-fixes.php
Check that the file pointer is truly returned when opening the logfile. This fixes situations where fopen returns false and fwrite attempts multiple times to write on to those false values. 
See #492
=> Check that logfile can be opened before writing (Related: #492)

js/upkeep.js
Remove the changes status ajax and JS side functions from under the window load function. This should fix the changes status feature not working. On the other hand, the JS window load function is excessive and unnecessary on this instance as well. 
See #494
=> Remove changes status feature from load function (Closes: #494)

lib/domain-tables.php
Fix fatal error with timestamp returning false and trying to pass it to `date_format()` function. Also, fix undefined subdomain array key warnings by checking they exist. The most crucial fix is the PHP fatal error fix. 
See #478
=> Fix PHP related fatal error and array key warnings (Related: #478)

js/sitestatus.js, lib/sitestatus-ajax.php, modules/check-site-health.php, modules/sitestatus.php, style/sitestatus.css
The feature adds a postbox to site status page on which users can run site checks. Site checks provides a report about good / pass and potential issues. 
Currently the checks include:
- HTTPS
- Recaptcha
- Deprecated plugins / features (currently wp-palvelu-plugin and https-domain-alias)
- Inactive plugins and themes
- Command `wp-test` status
- PHP error count
The checks are easily extendable as the check-site-health.php class can be extended by adding new logic. Note, translations are still to be done. 
See #66
=> Add a feature for checking site health

modules/sitestatus.php, modules/upkeep.php
Update "Technical Contacts" link on Site Status page to redirect directly to Contacts section on upkeep page.
#499
=> Add id and use it on link to redirect directly (Closes: #499)

modules/speed-test.php
Appended `#seravo-postbox-speed-test` to speedtest button on admin bar. It took me a while to understand what the button does as the speedtest postbox was at the bottom of the page. The button now scrolls down to speedtest postbox.
=> Make speedtest button scroll to speedtest postbox

modules/thirdparty-fixes.php
SQL logging now makes sure there's any queries preventing these PHP-warnings (with `WP_DEBUG`):
` Warning: Invalid argument supplied for foreach() in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/modules/thirdparty-fixes.php on line 118`
and useless sql.log entries:
```
...
...
```
Also now removes excess formatting from queries which had a lot of newlines, tabs, spaces etc.
They didn't look good in sql.log and made the reading just harder:
OLD:
```
SQL: 
SELECT comment_approved, COUNT( * ) AS total
FROM wp_comments
GROUP BY comment_approved
Time: 0.00067687034606934 s
Calling functions: require_once('wp-admin/admin.php'), require('wp-admin/menu.php'), wp_count_comments, get_comment_count
Query begin: 1616678768.5494
Custom data: Array
(
)
--
```
NEW:
```
SQL: SELECT …
```
=> Fix SQL log warnings and formatting

js/sitestatus.js
The result title didn't make much sense as HTTP cache clearly isn't working.
=> Fix HTTP cache status title

lib/security-ajax.php, modules/login-notification.php
- Fixes wp-login.log regex
-  Removes usage of `wp_timezone_string` so older core versions work
=> Fix timezone error

modules/check-default-options.php
The plugin uses an empty string as a false value. It means that the
user explicitly stated that they don't want the feature.
Do not override empty strings.
Closes: #514
=> Use strict comparison when checking for option existence

modules/instance-switcher.php
Removes some of the unnecessary information from the banner that is shown when inside a shadow. Now the user only sees the shadow comment instead of the previous "staging(comment)".
=> Improve shadow banners (Closes: #289)

modules/purge-cache.php
Excessive explicit buttons for dismissing purge cache notification caused not being able to actually dismiss the notification. As admin-notices implement the dismissing itself there's no need to explicitly add any buttons etc.
=> Make purge cache notification dismissible again

modules/dashboard-widgets.php
WP-admin dashboard widget with HTTP stats had a bug in the logic. Instead of showing the latest 4 months as intended, it was showing the first 4 months of the year. This is just a minor fix. 
For the widget see #5
=> Fix HTTP stats latest months logic

modules/logs.php
Command `wp-php-compatibility-check` has not been run on all sites thus when moving from upkeep page using the link "compatibility scan result" it shows the default `php-error.log` file. This can be confusing for the users if they start interpreting the php-error.log as compatibility log. This fixes the issue by checking whether log file exists and creates blank if not. 
There's internal issue about the fix / enhancement.
=> Check if PHP compatibility log file exists

style/common.css
Add common css file that contains dashboard error widgets, tooltip and "Toggle more" wrapper related css styles. Result wrapper css might need re-working when applying the styles for the new design. 
There are still some files, like `password.css`, that contain only a few styles. Should we move those under the common as well?
=> Add common css file

lib/postbox/template.php
Helpers include this far: 
- Paragraph
- Text / div field
- Section title
- Tooltip
- Spinner
- Button
- Success/Failure
Check that the created components are ok and they meet our requirements. 
See #538
=> Add multiple helpers to templates

js/postbox/seravo-ajax.js, src/lib/ajax/templates/auto-command.php, src/lib/ajax/templates/button-command.php, src/lib/ajax/templates/command-runner.php, src/lib/postbox/component/template.php, src/lib/postbox/postbox.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php
Adds option to dry-run with ButtonCommand. Also adds bunch of other fixes.
```
$db_cleanup = new Postbox\Postbox('backups-db-cleanup');
$db_cleanup->set_title(__('DB Cleanup test', 'seravo'));
$db_cleanup->set_build_func(array(__CLASS__, 'build_db_optimize'));
$db_cleanup->set_requirements(array( Requirements::CAN_BE_ANY_ENV => true ));
// Init optimize-db ajax handler
$db_cleanup->add_ajax_handler(new Ajax\ButtonCommand('cleanup-db'));
$db_cleanup->get_ajax_handler('cleanup-db')->set_command('wp-db-cleanup', 0, true, true);
$db_cleanup->get_ajax_handler('cleanup-db')->set_button_text(__('Cleanup database', 'seravo'), __('Dry-run', 'seravo'));
$db_cleanup->get_ajax_handler('cleanup-db')->set_empty_message(__('Nothing to cleanup!', 'seravo'));
$page->register_postbox($db_cleanup);
```
=> Add option to dry-run

src/lib/postbox/component/component.php, src/lib/postbox/component/template.php, src/modules/database.php, src/modules/sitestatus.php, src/modules/upkeep.php, style/common.css, vendor/composer/installers/.github/workflows/continuous-integration.yml
Rewrite 3 more widgets
- Site Info
- Tests Status
- Updates Status
Also, add a new template function for creating list elements. The function can take a set (array) or individual item when creating the list view. Fixes #548 as well by making sure that WP_Errors are caught if API errors for some reason.
Test the basic functionality for all 3 widgets. However, Update Status should probably be tested more extensively as there were lots of stuff on the original implementation (might have missed something or some formats wrong etc.).
=> Rewrite more widgets on upkeep and sitestatus pages

seravo-plugin.php, src/lib/ajax/handler.php, src/lib/postbox/component/template.php, src/lib/postbox/postbox.php, src/lib/postbox/requirements.php
Adds debug mode in Seravo Plugin. Debug mode can be used for all kinds of purposes but currently it's there to send no-cache header and to print debug info about the new postboxes.
In addition to basic info about the postbox, it measures the amount of time each postbox takes to render.
With the debug info table, we can easily see that all the postboxes have correct configuration. It's important to see that the requirements are correct (they currently are not, we must go through them later), caching is enabled where it can be enabled, data function is used where it can be used, the postbox doesn't slow page load time by too much and the postbox IDs and sections don't have any `-new` or `-2` suffixes.
Enable debug mode in: https://github.com/Seravo/seravo-plugin/blob/128f7f12e81ca49d7cce74e1 …
=> Add debug mode

modules/check-site-health.php
Use `strpos` instead of `str_contains` as the latter is introduced in PHP 8 and not all sites use it yet.
=> Fix deprecated plugins check

js/postbox/seravo-ajax.js, seravo-plugin.php, src/lib/ajax/handler.php, src/lib/ajax/response.php, src/lib/shell.php, src/modules/test-page.php, src/modules/toolbox.php
Adds possibility to run commands on background and polling to see when it has finished.
Also added a test-page which is enabled in Seravo Plugin debug mode and there's an example usage of polling.
Needed for long operations and related to https://github.com/Seravo/seravo-plugin/issues/465.
You can try the example on test-page.
=> Add background commands with polling

.travis.yml, src/lib/compatibility.php, src/modules/dashboard-widgets.php, src/modules/pages/database.php, src/modules/pages/sitestatus.php
Run PHPStan on CI as PHPStan has different output for different PHP versions and nobody has all the PHP versions installed locally. Running PHPStan is a must anyways as it doesn't tell about optional improvements but actual errors or errors waiting to happen.
This makes sure Seravo Plugin is always compatible with multiple PHP versions, not just the ones that's on the developers local machine and demo site.
Sadly we can't run PHPStan on PHP <7.1 but function signatures didn't really change much between 5.6->7.1 so I don't think we are missing anything and Seravo Plugin is dropping official 5.6 support anyways. The old 5.6 tests are still ran normally, this PR doesn't break anything, only adds more fail-safes.
Also fixes `seravo-plugin-2/master` PHPStan errors for PHP 7.1 and 7.4.
=> Run PHPStan on CI for PHP versions 7.1/7.4/8.0

src/lib/logs.php, src/modules/dashboard-widgets.php, src/modules/instance-switcher.php, src/modules/login-notification.php, src/modules/pages/sitestatus.php, src/modules/pages/upkeep.php
Ensure that `exec` and `substr` are used properly in Seravo Plugin. I don't think we should call the day off / close those issues yet, but this is a good step forward.
Related to #604 and #606
=> Ensure exec & substr compatibility

src/lib/helpers.php, src/modules/admin-checks.php, src/modules/dashboard-widgets.php
Move the PHP end of life and recommended version implementations to Helpers class.
#618
=> Move EOL and recommended PHP versions to Helpers (Closes: #618)

src/modules/pages/security.php, src/modules/passwords.php
- Format/Filter the wp-check-passwords output
- Remove return code from the wp-check-haveibeenpwned
Mostly related to #615, but because both are related to password checking also #625 minor fix included.
=> Enhance password checks (Closes: #615, #625)

src/modules/pages/database.php, src/modules/pages/security.php, src/modules/pages/sitestatus.php, src/modules/pages/upkeep.php
Fix the default positioning of the postboxes. Use `column3` and `column4` when appropriate and "balance" the postboxes overall.
#635
=> Fix default postbox positioning (Closes: #635)

src/lib/shell.php, src/modules/dashboard-widgets.php, src/modules/pages/sitestatus.php, src/modules/pages/test-page.php, src/modules/pages/upkeep.php
The old design ran 'du /data' every time the 15min/60min transient expired.
The command can take up to a minute causing a page to load really slow.
New design stores the last known disk size in a non-expiring transient.
When the main transient expires, it takes the last know size and
runs a background command to update the non-expiring transient from disk.
Found on a production site.
=> Rewrite disk usage fetching

composer.json, seravo-plugin.php, src/lib/geoip.php, src/lib/helpers.php, src/modules/geologin.php, src/modules/seravo-cli.php, vendor/composer/ClassLoader.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php
Adds GeoIP based login restricting. If the user tries to login from a country that's not in the list of countries from which login is allowed, error is shown on login (see screenshots).
Restrictions are only in use when there's at least on country on the list. So no restrictions enabled by default but if you were to add `Finland` to the list, you could only login from Finland from there on.
Adds WP-CLI commands to manage the restrictions:
```
PRODUCTION [@joosuakoskinen-4a5d38:~] $ wp seravo geologin
usage: wp seravo geologin allow <name> [--network]
or: wp seravo geologin disallow <name> [--network]
or: wp seravo geologin list 
```
The `geologin allow` adds a country to the allowed countries list. The `geologin disallow` removes entries from the allowed countries list. The `geologin …
=> Allow restricting login to specific countries

src/modules/pages/sitestatus.php
WP Corporate was not included in the plans array here:
https://github.com/Seravo/seravo-plugin/blob/42ecb9274e0699d099216878441784a59a3113e3/src/modules/pages/sitestatus.php#L761-L766
Closes: #659
=> Add WP Corporate to site plans in Site Status

js/common.js
Increases max TLD length from 4 to 6 so special domains are also accepted.
On upkeep page email form, try to input an email with longer TLD eg. `myemail@mydomain.agency`.
=> Fix validating emails with long TLD

composer.json, seravo-plugin.php
- Makes sure Seravo Plugin autoloader is loaded even if the site's global autoloader loads Seravo Plugin.
- Prevents new sites generating global autoloader for Seravo Plugin on deploy.
- Load a site and see no fatal errors.
=> Fix autoloading on sites using global autoloader

js/lib/ajax/seravo-ajax.js, src/lib/ajax/handler.php, src/lib/ajax/response.php, src/lib/api/container.php, src/modules/pages/sitestatus.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php, vendor/composer/installed.php
Instead of the Seravo Plugin's built-in poller, use Container API's `/task/` and `/shadow-reset/` endpoints to do it.
To be fixed at later time:
- Trying to reset an shadow (eg. from an other browser tab) while another shadow reset is in progress, will show a very generic error message to the user.
- The `SWD` and `Container` API classes are ugly, will replace the with some common `HTTPClient` system later.
- Have a site running with a Container API and at least one shadow site.
- Try breaking the "Shadows" (Varjot) feature on the site status (Sivuston tila) page.
=> Reset shadows using the Container API

style/common.css
Fixes long email addresses not being fully visible.
1. Make sure to clear browser cache (eg. `ctrl+f5`).
2. On upkeep page, add contact emails of different lengths.
=> Fix contact email button width

src/lib/api/container.php, src/modules/pages/upkeep.php
Use Container API to run the `php-compatibility-check` in the background instead of Seravo Plugin built-in poller. Functions exactly the same way expect it now doesn't allow to run multiple checks at once accidentally and the background task in more robust.
Still doesn't allow for live output or checking compatibility for a specific PHP version.
Depends on https://github.com/Seravo/seravo-plugin/pull/686, that's why there's an extra commit included.
The `php-compatibility-check` feature is on the upkeep page with the PHP version changer.
=> Implement php-compat-check with Container API

seravo-plugin.php, src/lib/api/container.php, src/modules/pages/backups.php
Use Container API to run the wp-backup-status in the background instead of Seravo Plugin running `exec`.
Note: This temporarily makes some extra API requests.
- Navigate to wp-admin > tools > backups.
- See backups status load fine.
=> Implement backup-status with Container API

src/lib/api/container.php, src/modules/pages/upkeep.php
Use Container API to run the `wp-php-set-version` in the background instead of Seravo Plugin running internal poller and `exec`.
Note: The old method used to print to a `php-version-change.log` log file and commit the changes to nginx configs. If these are still needed, they should be implemented in `wp-php-set-version`.
d to this PR, please link it here for context.
- Navigate to wp-admin > tools > upkeep.
- See PHP version change work fine.
=> Implement PHP version change with Container API

src/modules/pages/sitestatus.php
Instead of assuming `object-cache.php` to be under `/data/wordpress/htdocs/wp-content/`, use `WP_CONTENT_DIR` constant to determine to correct path.
- Have a custom path for `wp-content` dir.
- Navigate to dashboard > tools > site status.
- In the caching postbox, see that object-cache is OK.
- Run `mv object-cache.php object-cache.php.off`
- Install object-cache back with the install button.
- See that object-cache.php is installed and the `.off` file removed.
=> Allow object-cache.php to have a custom path

seravo-plugin.php, src/loader.php
According to the PSR-4 and PSR-12 standards, a class should be in a file of its own. The `src` directory doesn't follow the PSR-4 standard yet but will soon.
This also allows for more flexibility. This, for example, makes testing possible.
=> Move the Loader class to its own file

src/lib/security-restrictions.php
The complete blocking of `xmlrpc.php` seems to have been broken since it was implemented in https://github.com/Seravo/seravo-plugin/commit/23f2199f9df2f284a296f0ece196509991285112.
XML-RPC has never worked (when the full XML-RPC blocking was enabled) even though the `xmlrpc.php` file itself hasn't been blocked because Seravo Plugin has always removed all the XML-RPC endpoints.
In addition of fixing the blocking of `xmlrpc.php`, I changed it to respond with HTTP 403 instead of 200 so the blocking can be seen in access logs.
=> Fix XML-RPC blocking

.github/workflows/php-lint.yml, composer.json, seravo-plugin.php, src/lib/domains-ajax.php, src/lib/list-table.php, src/loader.php, src/test.php, src/vendor/ezyang/htmlpurifier/library/HTMLPurifier.autoload.php, tools/PHPCodeSniffer/Standard/ruleset.xml
- Removes legacy PHPCS rule exclusion comments. These are no longer needed with the new coding standard (909d4b4f528a1a55d4172ce28c2532c1b511816c).
- Updates the coding standard to be stricter by including new rules from the Slevomat coding standard (1af7527243af6817c497cbbb047cbb4672461e95).
- Fixes PHP syntax linting workflow by excluding the new `src/vendor` directory from being linted (46f38516ebe2af85e25d2caaa53e5198fdc9ccd9).
- Split PHP style linting to a separate workflow job so it's not ran with the full PHP version matrix (84333a06f4ac7f6a18a093272d7bb3cde5f054df).
No changes to actual code was made. If the GitHub action tests pass, everything should be ok.
=> Remove old PHPCS rules, improve coding standard and fix syntax workflows

.github/workflows/php-qa.yml, composer.json, seravo-plugin.php, tools/phpstan.neon
Adds workflow for running PHPStan. This workflow can later be used to run other QA tools too.
PHPStan currently only scans `seravo-plugin.php` for issues.
No code changes. Everything should be ok if the new workflow passes in https://github.com/Seravo/seravo-plugin/actions.
=> Add workflow for scanning for bugs and quality issues

src/modules/pages/upkeep.php
Replaces `wp_date` with PHP built-in function (since PHP 4) `date` because `wp_date` was introduced to WP core in version 5.3 and Seravo Plugin needs to support WP core 4.9.
Customer site had issues with older WP core.
1. Go to upkeep page and find PHP version postbox.
2. Make sure the PHP EOL dates are the same before and after this change.
=> Replace 'wp_date' with PHP built-in 'date'

.github/workflows/gnitpick.yml, .github/workflows/php-lint.yml, .github/workflows/php-qa.yml, src/modules/pages/sitestatus.php, tools/PHPCodeSniffer/Standard/ruleset.xml
- Add missing plan names to site status array
Start and dev plans show an empty string in the site status page.
=> Add missing plans to Site Status

src/lib/cruftremover.php
Add missing `self::` to rmdir_recursive() call.
=> Fix 'Call to undefined function Seravo\rmdir_recursive()' error

src/modules/thirdparty-fixes.php
It was noticed that the format of MainWP options was changed in newer versions of MainWP plugin. This caused issues when SP tried to override the value for README file removal, as config value was no longer treated as array.
Closes: SP-13
If there is an issue related to this PR, please link it here for context.
=> Check the type of MainWP options before access
