Seravo/seravo-plugin

- composer.json
- lib/reports-page.php
- modules/reports.php
- wp-palvelu-plugin.php
Initially customers can view HTTP request stats from the Reports page.
> Add new Reports page

- lib/reports-ajax.php
- lib/reports-page.php
- modules/reports.php
* Improve stats listing with summary bar graphs.
* Report disk size, as it is important for the customer to know their resource usage.
* Show multiple site health checks.
> Extend Reports page

- modules/instance-switcher.php
> Fix a bug where the user is notified that menuclass is not defined

- .travis.yml
Current implementation returns true always.
> Travis CI: Actually fail if php syntax checking fails

- js/color-hash.js
- js/reports-chart.js
- lib/reports-ajax.php
- lib/reports-page.php
> Demonstration of skill

- js/log-viewer.js
- modules/logs.php
- style/log-viewer.css
- Change log rows hover-effect
- Fix log-views overlay-effect to full-width
- Add log-view-active box under log-view-table
- Add a script when log is clicked, display it in the log-view-active box
- Fix log-viewer.css code
- Fix log-viewer.js indentation
> Make logs-tool more readable

- js/database.js
Pull request "Update Database-tool layout to WordPress layout" didn't work correctly.
Here is fix to that.
```
'use strict';
jQuery(document).ready(function($) {
});
```
> Use ready() to make a function available after the document is loaded

- lib/reports-ajax.php
> Show stderr when reporting WP data integrity

- lib/cruftfiles-ajax.php
> Suggest to remove files with wp core checksum

- lib/cruftfiles-ajax.php
Removing files from plugins and themes is generally not advisable. The cruft remover in it's current state can suggest the user such files and directories which might have unintended effects as mentioned in #101 . In this PR such items are not suggested to the user, making the cruft remover safer for the user.
> Remove files in plugins and themes from suggested cruft

- lib/cruftfiles-ajax.php
This PR fixes the bug introduced in dbb0cec
> Fix cruft deletion bug

- lib/reports-page.php
GoAccess' reports couldnt be reached. There was extra quotation marks, now links should work.
Closes #127 .
> GoAccess reports issue Closes #127

- js/cruftfiles.js
- modules/cruftfiles.php
- style/cruftfiles.css
The user is given an option of selecting multiple items considered as cruft and removing from the server.
Choosing **Select All** chooses all the items on the list, including it's counterpart on the bottom of the list.
Deselecting any item from the list removes the **Select All** selection.
If all items are deleted, the Cruft remover returns to it's empty state.
> Improve Cruft Remover UI

- lib/helpers.php
- modules/backups.php
- modules/cruftfiles.php
- modules/database.php
- modules/instance-switcher.php
- modules/login-notification.php
- modules/logs.php
- modules/optimize-images.php
- modules/passwords.php
- modules/relative-urls.php
- modules/reports.php
- modules/shadows.php
- modules/tests.php
- modules/updates.php
- phpcs.xml
This PR updates Seravo-plugin coding standards.
> Update coding standards

- seravo-plugin.php
This PR limits the use of the cruft remover to administrators only.
> Adjust cruft remover user rights

- modules/reports.php
> Implement new section on Reports page showing page info

- lib/updates-page.php
> Show screenshots from last update attempt on the Updates page

- js/purge-cache.js
These are some things that I noticed in my local development that should be fixed before release 1.9.3.
> Small improvements to the purge cache functionality

- lib/domains-dns.php
- lib/domains-page.php
- modules/domains.php
It may not be pretty, but it should work as expected!
Before merging, the internal API should be updated first.
> Add a GUI for editing zones

- lib/domains-dns.php
- lib/domains-page.php
- modules/domains.php
Fixes the following problems with domain zone editing:
- Editing does nothing (Because of 2 nested forms)
- API errors with subdomains (Subdomains don't have zones)
- Styling not updated everywhere
- No proper support for multiple pages (Always returned to 1st page)
> Fix domain zone editing

- js/seravo-postbox.js
There was a notice that undefined pagenow broke Visual Composer.
This simple fix solves the problem.
> Fix 'pagenow not defined'

- lib/domains-page.php
Instead of showing 'Array', columns list the DNS data.
> Display DNS data as string

- modules/instance-switcher.php
- style/instance-switcher.css
- style/purge-cache.css
The commit will make the purge cache and instance switcher features available for mobile devices. It'll also remove the text and only show the icon for the features when the screen size goes below a certain amount.
> Improve UI on mobile devices

- lib/mails-page.php
- modules/mails.php
- seravo-plugin.php
- style/mails.css
Adds a page that lists all email addresses with forwards for a specific domain.
> Add mail forwards page

- js/cruftfiles.js
- lib/updates-page.php
- style/cruftfiles.css
- style/database.css
- style/instance-switcher.css
- style/log-viewer.css
- style/login-notification.css
- style/mails.css
- style/optimize-images.css
- style/purge-cache.css
- style/seravo-postbox.css
- style/tests.css
- style/updates.css
- I deleted unnecessary !important tags
- I added more specific classes when necessary
- I deleted conflicting classes/styles
- I deleted unnecessary tabs
- I cleaned the code also by adding line breaks after every class, so style-files could be readed more easily
> Clean the code (Closes: #180)

- js/mails.js
- lib/mails-page.php
- modules/mails.php
- style/mails.css
Makes the following improvements to the mails page:
- Fixes problem told by @mikkoaf in #214 
- Adds a better design using postbox to make the page better looking and more responsible
> Mails page improvements

- js/updates.js
- lib/updates-ajax.php
- modules/updates.php
This PR will add "PHP version change" postbox to Updates-page.
This PR does not include updating all of the Updates-page into using postboxes.
> PHP Version change widget

- docs/README.md
- lib/canonical-domain-and-https.php
- lib/mails-page.php
- lib/security-restrictions.php
- modules/backups.php
- modules/security.php
- seravo-plugin.php
A picture tells more than a thousand words..
> New security page

- js/updates.js
- modules/updates.php
> Move rest php-switcher-postbox strings to updates.php

- modules/fixes.php
> Remove WP Core Site Health update check

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This PR addresses https://github.com/Seravo/seravo-plugin/issues/231. I have a feeling that there is something very essential missing from the CONTRIBUTING.md file here, so I would appreciate another pair of eyes skimming through this with time. :)
> Add a CONTRIBUTING.md file and a pull request template

- js/domains.js
- lib/domains-dns.php
This commit makes the publish button work with the new AJAX system.
This is a subtask of #245
Domains page
- Start with a domain which has not been published
- Publish it through domains page.
- Test editting of zone (for regressions)
> Fix the publish button in zone edit

- seravo-plugin.php
Simply bump the version to 1.9.9
> Bump version to 1.9.9

- modules/check-php-version.php
- modules/updates.php
- Fixes HTTP_REFERER undefined notice reported in #252
- Removes usage of useless undefined variable on updates page
> Fix a couple of undefined notices

- js/instance-switcher.js
- modules/instance-switcher.php
- Adds Seravo Plugin side support for shadows with domain (more in commit message)
- Makes the functionality of instance switcher more constant
Problem reported in issue #67
Reviewer should try accessing and exiting different shadows in different ways (url / instance-switcher / shadow banner). Site 'joosuakoskinen' in Sestak can be used for testing. It has 2 shadows, one with domain and one without.
> Improve shadow domain support

- lib/canonical-domain-and-https.php
> Add 'headers_sent' check to the https redirect

- modules/sitestatus.php
- modules/toolbox.php
This PR includes:
- Change the Seravo Toolbox class name
- Change the URL of "optimize images" article
1. Seravo Toolbox will not load if the site contains BadabingBreda's "Toolbox for Beaver Builder" plugin (https://www.beaverplugins.com/)
2. #301
> Minor fixes for Seravo Toolbox

- lib/domains-page.php
- modules/security.php
- modules/sitestatus.php
Some of the "beta"-titles have been there
for a really long time and they are not
neccessary anymore.
Only kept the title for mail forwards postbox
as it's going to be under major development
soon.
> Remove old "beta"-titles

- modules/instance-switcher.php
- modules/sitestatus.php
To decrease amount of calls to /domains endpoint,
SWD API moved shadow domains to /shadows. This
makes use of that.
https://github.com/Seravo/swd/commit/e292a2cbc7c0956f5b203db8ae2d5993ff482dff
> Use /shadows endpoint for shadow domains

- lib/cruftfiles-ajax.php
- modules/security.php
Adds some new known cruft files/dirs and
also searches for cruft in home directory.
Closes: #308.
Create some files matching the cruft specifications
and let cruftfiles remover on security page take care of them.
> Add searching cruft from home directory

- lib/security-ajax.php
- Makes wp-login.log parser merge only the successful lines to login data to prevent memory exhaustion
- Reverses the data order so the latest login is first.
Issue #326, this was a problem on at least one site (with 20-100k 'fail' lines in all wp-login files and only few successful ones).
> Read only successful wp-login.log lines (Closes: #326)

- lib/sitestatus-ajax.php
Replaces '`exec(redis-cli...`' with phpredis to improve stability,
maintainability and readability. The UI stays the same.
Issue #331.
> Use phpredis instead of redis-cli (Closes: #331)

- modules/upkeep.php
Replaces the "Site Status" postbox title with "Update Status".
The translations will be added before publishing the next version.
Issue: #357
> Rename "Site Status" postbox (Closes: #357)

- js/database.js
- style/database.css
- style/security.css
Makes the cruft files and search-replace postboxes more compact and
allows some text wrapping to be done so the content doesn't overflow
on some viewport sizes.
Issue: #337
> Fix postbox overflow (Closes: #337)

- lib/cruftfiles-ajax.php
Excludes all directories containing only whitelisted
dirs or files.
This allows excluding dirs which are automatically recreated
on page load by adding all the files in that dir in whitelisted_files
array.
Already added the dirs reported in #339.
Issue: #339
> Exclude automatically recreated dirs (Closes: #339)

- modules/check-https.php
- modules/security.php
- modules/upkeep.php
Old help article links are replaced with links to new ones.
Issue: #365
> Replace old links with new ones (Closes: #365)

- lib/domain-tables.php
- modules/backups.php
- modules/sitestatus.php
- modules/upkeep.php
- style/cruftfiles.css
- style/domains.css
- style/seravo-postbox.css
New styling for h3 and h4 headings and better alignment of content in some postboxes.
Issue: #389
Uniform content alignment throughout the plugin makes the UI feel more professional.
Look headings for example in "Seravo Updates" postbox.
Look content alignment for example in "Backups", "Unnecessary Themes" and "Mails" postboxes.
> Small styling fixes

- modules/upkeep.php
Adding min and max attributes for the datepicker so that users have some kind of visuals for the 30 days maximum since date. This concerns the feature https://github.com/Seravo/seravo-plugin/pull/392.
> Enchance the datepicker by adding min and max dates

- js/database.js
> Round database autoload size to two decimals

- modules/thirdparty-fixes.php
This makes it much easier to debug SQL queries site is generating. If SAVEQUERIES is set true, WordPress core stores all queries in $wpdb->queries, and now we also begin logging those queries to /data/log/sql.log.
Sometimes we encounter sites that use excessive amounts of database resources. This makes it easier to debug what's happening inside WordPress.
This shouldn't do anything if SAVEQUERIES isn't defined or value isn't `true`. If however wp-config.php contains
```php
define('SAVEQUERIES', true);
```
this should log all SQL queries to `/data/log/sql.log`.
> Log SQL queries if SAVEQUERIES is set to true

- modules/sitestatus.php
Give individual ids and names for the submit buttons. Previously they were both just "btnSubmit".
Related to #459
> Add individual id and name for the submit buttons (Related: #459)

- style/database.css
- style/sitestatus.css
- style/upkeep.css
Fixes some of the margins in the plugin so elements are no longer right next to each other. Also fixes some of the small issues with the css with different screen sizes.
Some of the margins didn't work properly with different screen sizes and caused some of the elements to appear misaligned. After the fixes the elements should look okay on most modern screen sizes.
**Before**
**After**
> Fix margins

- modules/thirdparty-fixes.php
This allows developers easily enforce caching of HTTP requests to
certain domains. This makes it easy to eg. force caching of slow API
queries etc.
Example, to cache POST and GET requests to api.wpml.org, one could write
add_filter('seravo_cache_http_post_api_wpml_org', '__return_true', 10, 1);
add_filter('seravo_cache_http_get_api_wpml_org', '__return_true', 10, 1);
in eg. functions.php.
Note: This doesn't currently check that eg. ports match.
Add new filters to enable cache enforcing.
This allows easily caching certain third-party API requests that return data very slowly, and then cause horrible slowdowns. As we have no control of those third-party servers there is very little we can do to make them always perform good > second best option is to reduce number of requests against them. …
> Allow caching of HTTP requests to certain domains

- seravo-plugin.php
Quick fix for `undefined array key "report"` warnings issued when going to upkeep page. 
See #486 and #478
> Check array key at get (Related: #486, #478)

- lib/backups-ajax.php
- lib/cruftfiles-ajax.php
- lib/cruftplugins-ajax.php
- lib/cruftthemes-ajax.php
- lib/database-ajax.php
- lib/db-cleanup-ajax.php
- lib/domain-tables.php
- lib/domains-ajax.php
- lib/search-replace-ajax.php
- lib/security-ajax.php
- lib/sitestatus-ajax.php
- lib/upkeep-ajax.php
- modules/backups.php
- modules/database.php
- modules/domains.php
- modules/security.php
- modules/sitestatus.php
- modules/upkeep.php
- modules/wp-cli.php
Ensure that all modules under folders lib/ and modules/ are properly namespaced. Note, please also test carefully the modules etc. in case of any errors. I've tested all the pages comprehensively and all features and functionality seem to work alright / normally as before. 
See #466
> Ensure seravo namespace usage on all modules (Closes: #466)

- modules/upkeep.php
Fix test status showing as "failure" when no tests have been ran yet.
> Fix test status on new sites

- lib/security-ajax.php
The function should only list successful logins but
there were some failed logins too. Fixed now.
> Fix last successful logins

- README.md
Update and clarify the translation process on README. Basically, add instructions how to fully update translations.
In general, documentation for making translations should be available fully rather than partially. This also seems to be something that people forget quite often and thus documenting it is beneficial for all.
> Clarify the translation process on README

- lib/cruftfiles-ajax.php
- lib/helpers.php
Fixes some bad code in cruftfiles feature.
> Improve coding practices in cruftfiles

- lib/domain-tables.php
- lib/security-ajax.php
- modules/instance-switcher.php
- modules/upkeep.php
**Bug fixes:**
- Fix domains-page PHP reference restriction notice:
`PHP Notice: Only variables should be passed by reference in ...`
- Fix hook_suffix warning on domains-page:
`PHP Warning: Undefined array key "hook_suffix" in ...`
- Fix Seravo Plugin updater button classes
- Check if `/shadows` endpoint returned domains, dont assume
- Remove usage of `wp_timezone_string()` in security-ajax, it's too new
- Initialize some variables before using them
- Fix `update.log` parsing on upkeep page as log format changed
> Fix some small bugs

- modules/logs.php
Ensure that logfiles can only be read under `/data/log` directory.
> Check that filepath is valid when reading logs

- modules/instance-switcher.php
Method argument default value.
#534  
ASAP
See issue.
See issue.
> Fixes gravityforms issue #534

- js/postbox/seravo-ajax.js
- lib/postbox/ajax.php
- lib/postbox/component.php
- lib/postbox/handler.php
- lib/postbox/postbox.php
- lib/postbox/template.php
- rector.php
Adds AJAX handler and pre-made postbox for automatically sending AJAX request and running a command on page load.
Also fixes a couple of bugs.
Example usage here:
https://github.com/Seravo/seravo-plugin/blob/postbox/upgrade-backups-page/modules/backups.php#L35-L53
> Add Ajax handler and postbox for auto-command

- src/lib/postbox/component/template.php
- style/common.css
- Add optional class parameters
- Use common.css instead of styles inside element
> Misc improvements to template helpers

- js/postbox/seravo-ajax.js
Fixes LazyLoader spinner not showing.
> Fix LazyLoader spinner

- src/lib/postbox/component/template.php
- src/modules/security.php
- src/modules/sitestatus.php
- style/common.css
Rewrite the HTTP Request Statistics postbox.
- Add some CSS styles
- Fix a bug with link template
- Add optional tooltips for table view
> Rewrite HTTP Request Statistics postbox

- js/upkeep.js
- src/lib/postbox/component/template.php
- src/lib/upkeep-ajax.php
- src/modules/upkeep.php
- style/common.css
Rewrite Seravo Plugin update and Change PHP version postboxes. Also, add radio button to templates and rewrite PHP compatibility check to use the new AJAX poller.
Also, removed some excessive AJAX and JS files that could have caused issues with the new design. These files should be fully removed when the rewrite is complete on the given page.
> Rewrite some upkeep page postboxes

- js/charts.js
- js/reports-chart.js
- js/sitestatus.js
- src/lib/ajax/templates/lazy-loader.php
- src/lib/postbox/component/template.php
- src/lib/postbox/templates/lazy-loader.php
- src/lib/postbox/toolpage.php
- src/lib/sitestatus-ajax.php
- src/modules/sitestatus.php
- style/common.css
- style/sitestatus.css
Rewrite the disk usage with the new postbox design and chart handling.
- Add flag variable to LazyLoader AJAX for `<hr>` element
- Change the layout a bit
> Rewrite disk usage postbox

- src/modules/pages/sitestatus.php
Rewrites sanitize uploads postbox to use the new settings wrapper.
This PR is based on https://github.com/Seravo/seravo-plugin/pull/589, that must be merged first. The extra commit is from that PR.
> Rewrite sanitize uploads postbox

- src/lib/postbox/component/settings.php
- src/modules/pages/sitestatus.php
Rewrites optimize images postbox to use the new settings wrapper.
This PR is based on https://github.com/Seravo/seravo-plugin/pull/589 and https://github.com/Seravo/seravo-plugin/pull/590, they must be merged first. The two extra commits are from them.
> Rewrite optimize images postbox

- phpstan.neon
- seravo-plugin.php
Tell PHPStan this constant is used as a variable/switch.
From https://github.com/Seravo/seravo-plugin/pull/593#discussion_r676519468
> PHPStan's dynamicConstantNames

- js/lib/ajax/seravo-ajax.js
- src/modules/pages/upkeep.php
Enhance the already re-written Seravo Plugin Updater postbox.
- Add a proper error handling for failed command
- Error log installation issues and recommend making an issue on Github
- Reload the page if installation run
The reload after installation is now done by using `location.reload()` as AJAX function not returning response / trying to redirect somewhere else will cause JS side `on_error`. Not sure if it's the best implementation, but please let me know how we could fix it for better 👍🏼.
> Enhance Seravo Plugin Updater postbox

- src/lib/compatibility.php
- src/lib/helpers.php
- src/modules/dashboard-widgets.php
- src/modules/pages/sitestatus.php
- style/common.css
Rewrite the dashboard widgets module. AJAX is not included on dashboard widgets, but it can most likely be added later on if wanted. 
- Use the new postbox design for creating the widgets
- Some minor refactoring and renaming.
> Rewrite the dashboard widgets

- src/lib/ajax/response.php
- src/lib/ajax/templates/fancy-form.php
- src/lib/ajax/templates/lazy-command.php
- src/lib/ajax/templates/simple-command.php
- src/modules/pages/database.php
- src/modules/pages/security.php
- src/modules/pages/sitestatus.php
- src/modules/pages/test-page.php
- src/modules/pages/upkeep.php
Unify and enhance AJAX responses
- Enhance command error response
- Add api error response
- Use template responses instead
Should there be something else to enhance regarding the AJAX responses, please let me know
> Unify and enhance responses

- src/lib/helpers.php
- src/modules/pages/backups.php
- src/modules/pages/database.php
- src/modules/pages/sitestatus.php
Misc minor fixes and improvements. Remove some excessive lines etc.
- Hide backups info on development
- Make all database postboxes visible on staging & development
- Adminer link when on development
Doesn't include any fixes for cruftremover as it might be better to debug those issues separately.
Related to #626
> Misc fixes and improvements

- phpstan.neon
- seravo-plugin.php
- src/lib/postbox/requirements.php
- src/modules/pages/backups.php
- src/modules/pages/database.php
- src/modules/pages/domains.php
- src/modules/pages/security.php
- src/modules/pages/sitestatus.php
- src/modules/pages/upkeep.php
- src/modules/speed-test.php
Closes: #622 #616 
- Fix super-admins not being able to access tools.
- Adds super-admin requirement for postboxes that can break or modify site functionality used wrong (search-replace etc). Super-admin requirement only applies to multisites.
- Adds admin requirement for speed test button.
> Fix issues with requirements

- js/updates.js
- src/lib/domain-tables.php
- src/modules/pages/backups.php
- src/modules/seravo-cli.php
Closes: #617, #624, #623, #619
- Fixes Slack webhook
- Fixes wp-backup-status ran before first backup
- Removes WP CLI 'seravo updates' from dev and staging envs.
- Fix zone sniff on finnish sites.
> More misc fixes

- seravo-plugin.php
- src/lib/cruftremover.php
- src/lib/postbox/handler.php
- Fixes cruftremover in development environment
- Fixes `add_file_information` bugs
- Check that transients exists
- Stop calling get_transient in loops
https://github.com/Seravo/seravo-plugin/issues/626
> Fix misc cruftremover bugs

- src/lib/domain-tables.php
- src/lib/postbox/handler.php
- src/modules/dashboard-widgets.php
- src/modules/pages/sitestatus.php
- Limit HTTP report count on site status page
- Only load Seravo postbox scripts/styles on pages they are needed (tool pages and partly dashboard)
> Fix bugs found on production sites

- src/lib/helpers.php
Parse available, recommended and EOL versions from /etc/php/versions.
The code is mostly same as in https://github.com/Seravo/seravo-plugin/pull/653 so the review from there should so OK here too. The EOL notification should be reviewed again.
> Parse PHP versions from local file

- seravo-plugin.php
Bump version to 1.9.39. There seems to have been a tag for 1.9.38 even though the version was 1.9.37  so bumped to 1.9.39.
Doesn't need testing but needs an approval.
> Bump version to 1.9.39

- src/modules/wp-login-log.php
It was noticed that when user has enabled two-factor plugin on their site, and provides correct credentials and 2FA/MFA succeeds, the login event didn't end up in our login logs.
This happens because two-factor plugin modifies the login flow and shows additional forms for doing the MFA validation.
Missing such information in logs it's at least a user experience problem, as our customers assume they see all relevant events in the logs. It might also be security issue, if trust model requires such data to be in this log, in addition to other possible audit logs.
Fixes issues where certain events not logged correctly.
Ensure that logging works in all these scenarios:
- two-factor not installed, successful login
- two-factor not installed, failed login
- two-factor installed and activated, …
> Hook successful login action in two-factor plugin

- src/modules/pages/upkeep.php
All hard coded PHP version numbers have been removed. The latest versions are now on the list. Version with EOL date passed is not listed unless it's in use. The EOL date is now translated. EOL date is shown only if it has passed or is in less than 12 months. 
Old:
New:
> Fix PHP version changing

- src/modules/thirdparty-fixes.php
Read the commit message from https://github.com/Seravo/seravo-plugin/commit/9ea766e39450befe202c0957cccb0c92c9e75142 by @ypcs.
> Prevent MainWP from removing README.html

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Fix issue template grammar
Nothing particular
> Update issue template grammar

- js/lib/ajax/seravo-ajax.js
- src/lib/ajax/handler.php
- src/lib/ajax/response.php
- src/lib/api/container.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
- vendor/composer/installed.php
Adds the base for Container API Client and the possibility to run background tasks with polling.
Container API is not used anywhere yet.
> Add Container API client

- js/lib/ajax/seravo-ajax.js
- src/lib/ajax/handler.php
- src/lib/ajax/response.php
- src/lib/api/container.php
- src/modules/pages/sitestatus.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
- vendor/composer/installed.php
Implement shadow-reset using Container API.
Depends on https://github.com/Seravo/seravo-plugin/pull/686, that's why there's an extra commit included.
> Add shadow-reset using Container API back

- seravo-plugin.php
Bump version to 1.9.42.
Changelog for the version:
- Container API `php-compatibility-check` (https://github.com/Seravo/seravo-plugin/commit/b6d374af78ce5d561eeb2cbe0cd893106115f774)
- Container API `wp-shadow-reset` (https://github.com/Seravo/seravo-plugin/commit/feac58a2749a772e442eb911502a5169b88ce848)
- Container API client (https://github.com/Seravo/seravo-plugin/commit/09e2f66cd3e15d6680c68dbac91e937b8864dcb0)
- Development docs (https://github.com/Seravo/seravo-plugin/commit/86cd92792d0f2c64f4655eb0831a2870a21c9391, https://github.com/Seravo/seravo-plugin/commit/76148a068d4d048c82aa10b611d41a094ae80201, https://github.com/Seravo/seravo-plugin/commit/7bda2c26e3b987e23c9924b2d488de9988d8c0fc)
- Project cleanup (https://github.com/Seravo/seravo-plugin/commit/ce5eedfc4f4557b0307c28f956d …
> Bump version to 1.9.42

- seravo-plugin.php
> Bump version to 1.9.43

- .github/workflows/gnitpick.yml
Adds a workflow for validating commit author's email and the commit message format.
> Add the gnitpick workflow

- src/lib/api/container.php
This makes it much easier to trace why certain features have failed.
See: <https://www.php.net/manual/en/function.error-log.php>
> Log all API errors

- seravo-plugin.php
Also: begin using semantic versioning to make versions easier to interpret for humans too.
> Bump version to 1.10.0

- seravo-plugin.php
If there is an issue related to this PR, please link it here for context.
> Bump version to 1.10.1

- seravo-plugin.php
- src/lib/api/container.php
- Fix API error with php_compatibility_check
- Bump version to 1.10.2
Currently SP sends bad JSON if no version is specified, resulting in API error.
> Fix API error with php_compatibility_check

- src/lib/cruftremover.php
This prevents directory traversal in case of symlinks while going through path labeled with cruft remover.
> Remove symlinks separately in cruft remover

- seravo-plugin.php
Applies bugfixes in cruft remover tool.
> Bump version to 1.10.3

- seravo-plugin.php
> Bump version to 1.10.4
